profiler:
  service: <service-name>
  version: 1.0.0
  version_path: v1

server:
  port: 9090
  metrics: 9091

sentry:
  dsn: ""
  env: dev
  debug: true
  traces_sample_rate: 1.0

hmac_internal:
  secret_key: ""
  algorithm: sha256
  allowed_clock_skew: 300
  access_key: ""

logging:
  level: "debug"

redis:
  host: localhost
  port: 6379
  database: 9
  rate_limit_database: 5
  ttl: 1h
  pool_size: 100
  username: ""
  password: ""
  min_idle_conns: 10
  write_timeout: 10s
  read_timeout: 10s
  dial_timeout: 5s